version: '3'

services:
  redis:
    image: redis
    ports:
    - "6379:6379"

  routing:
    stdin_open: true
    tty: true
    image: langhaarzombie/beehive-routing
    ports:
    - "5671:5671"
    env_file:
    - .env
    depends_on:
    - redis

